"""empty message

Revision ID: f3bbcd159c7c
Revises: 
Create Date: 2018-01-22 19:16:11.291608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3bbcd159c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.alter_column('book', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_table('article',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('article_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('article_content', mysql.TEXT(), nullable=True),
    sa.Column('article_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='article_book_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
